### ISSUE TITLE
Klipper load balancer

### ISSUE THREAD

**Issue by samcday** [samcday/home-cluster#86]
Once #85 is done and there's some hcloud nodes connected to the cluster, deploy the [klipper](https://github.com/k3s-io/klipper-lb) load balancer to run on those nodes.

This should finally make arbitrary public TCP/UDP ingress possible. Currently only arbitrary ingress on tailnet, or HTTP(s) with Cloudflare Tunnels / Tailscale funnel is possible.

**Comment by samcday** [comment]
Sigh. Of course nothing is ever straightforward.

Turns out the "Klipper" (which is just the original name for k3s) load balancer thing (which prefers to be called "servicelb" now, even though the some of the repos are still named Klipper) is *not* standalone. The image used in servicelb-* pods is in a separate repo (the one linked in original issue comment). But the controller that reconciles all this crap is just [sitting in the k3s codebase](https://github.com/k3s-io/k3s/blob/master/pkg/cloudprovider/servicelb.go).

Here's the thing though. The code is pretty simple. As I would expect from something that just reconciles a couple of pods and then glues some crap into `.status.addresses` on the reconciled LB Service.

So I'm gonna try ripping that code out and building + running it standalone.

**Comment by samcday** [comment]
[Official acknowledgement](https://github.com/k3s-io/helm-controller/issues/206#issuecomment-1741182276) on the state of things.

Also: if I can get the translocated code to work easily enough, I'd be tempted to do a rewrite of the controller in Rust. The Go impl is only 500 lines. If I rewrote it I'd make the load balancer classes dynamic based on a CRD. i.e:

```
apiVersion: awesome.shit.dawg/v0defsrunyourprodshitonthisyo
kind: HostLoadBalancerClass
metadata:
  name: used-in-loadBalancerClass-of-lb-services
spec:
  nodeSelector:
    i-go-in-front: ok
  replicas: 2
```
